version: '3.8'

services:
  backend:
    container_name: tts-backend
    build:
      context: ./backend
    image: tts-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./shared_storage:/shared_storage
      - ./model_registry:/model_registry
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/shared_storage/hf_cache

      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  frontend:
    container_name: tts-frontend
    # build:
    #   context: ./frontend
    image: tts-dashboard:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0 --port 3000
